
const CloudHomePage = require('../pageobjects/cloudHome.page')
const SearchResultsPage = require('../pageobjects/searchResults.page')
const CalculatorPage = require('../pageobjects/calculator.page')
const Estimate = require('../pageobjects/estimate.page')
const EmailDialog = require('../pageobjects/emailDialog.page')
const TempEmailMainPage = require('../pageobjects/tempEmailMain.page')
const GeneratedEmailPage = require('../pageobjects/tempEmailGenerated.page')
const MailBoxPage = require('../pageobjects/mailBox.page')

describe('Calculator test', function () {
  it('Hurt me plenty', async function () {
    await CloudHomePage.open()
    await CloudHomePage.searchInput.click()
    await CloudHomePage.searchInput
      .keys(['Google Cloud Platform Pricing Calculator', 'Enter'])
    await SearchResultsPage.resultsBox.waitForDisplayed()
    await SearchResultsPage.searchResults[0].click()
    await (await (await (await (await (await (await (await (await (await CalculatorPage.calcInit())
      .setNumberOfInstances('4'))
      .setOptionsInTo('series', 'N1'))
      .setOptionsInTo('machineType', 'n1-standard-8 (vCPUs: 8, RAM: 30GB)'))
      .clickAddGPUCheckbox())
      .setOptionsInTo('GPUtype', 'NVIDIA Tesla P100'))
      .setOptionsInTo('GPUnumber', '1'))
      .setOptionsInTo('localSSD', '2x375 GB'))
      .setOptionsInTo('dataCenterLocation', 'Frankfurt (europe-west3)'))
      .setOptionsInTo('committedUsage', '1 Year')
    await CalculatorPage.addToEstimateButton.click()
    await expect(Estimate.vmClass).toHaveTextContaining('Regular')
    await expect(Estimate.instanceType).toHaveTextContaining('n1-standard-8')
    await expect(Estimate.region).toHaveTextContaining('Frankfurt')
    await expect(Estimate.localSSD).toHaveTextContaining('2x375 GiB')
    await expect(Estimate.commitmentTerm).toHaveTextContaining('1 Year')
    await expect(Estimate.finalPrice).toHaveTextContaining('USD 4,024.56')
  })

  it('Hardcore', async function () {
    await Estimate.emailBtn.waitForDisplayed()
    await Estimate.emailBtn.click()
    await browser.newWindow('https://yopmail.com/')
    const openedPages = await browser.getWindowHandles()
    await TempEmailMainPage.emailgenerator.click()
    await GeneratedEmailPage.copyEmailBtn.click()
    await browser.switchToWindow(openedPages[0])
    await CalculatorPage.calcInit()
    await EmailDialog.emailInput.addValue(['Shift', 'Insert'])
    await EmailDialog.sendEmailBtn.click()
    await EmailDialog.dialogContainer.waitForDisplayed({ reverse: true })
    await browser.switchToWindow(openedPages[1])
    await GeneratedEmailPage.checkEmailBtn.click()
    await MailBoxPage.waitForMail()
    const textInMail = await MailBoxPage.getPriceFromMail()
    await browser.switchToWindow(openedPages[0])
    await CalculatorPage.calcInit()
    await expect(Estimate.finalPrice).toHaveTextContaining(textInMail)
  })
})
